build:ios:
  stage: build
  tags: ["mac-mini"]
  script:
    - pod install --repo-update
    - pwd
    # - sed 's/fileprivate let tableView =/public let tableView =/g' ./Pods/DropDown/DropDown/src/DropDown.swift > tmp.swift && mv -f tmp.swift ./Pods/DropDown/DropDown/src/DropDown.swift
    - xcodebuild archive -scheme linphone -archivePath ./linphone.xcarchive -configuration Release -workspace ./linphone.xcworkspace -UseModernBuildSystem=YES -destination 'generic/platform=iOS' -allowProvisioningUpdates
    - xcodebuild -exportArchive -archivePath ./linphone.xcarchive -exportPath ./linphone-adhoc-ipa -exportOptionsPlist ./linphone-adhoc.plist -allowProvisioningUpdates -UseModernBuildSystem=YES -destination 'generic/platform=iOS'
  artifacts:
    paths:
      - linphone.xcarchive
      - linphone-adhoc-ipa
    when: always
