build:ios:
  stage: build
  tags: ["mac-mini"]
  script:
    - bundle install
    - bundle exec fastlane build_release
  # artifacts:
  #   paths:
  #     - linphone.xcarchive
  #     - linphone-adhoc-ipa
  #   when: always
