update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_release do
    unlock_keychain
    cocoapods
    get_certificates
    get_provisioning_profile(
      app_identifier: "com.acceleratenetworks.linphone",
      cert_id: Actions.lane_context[SharedValues::CERT_CERTIFICATE_ID],
    )
    gym(
      clean: true,
      configuration: "Release",
      output_directory: "builds/",
      output_name: "an-mobile-release.ipa",
      scheme: "linphone",
      workspace: "linphone.xcworkspace",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        provisioningProfiles: {
          "com.acceleratenetworks.linphone" => "com.acceleratenetworks.linphone AppStore 1685121971"
        }
      }
    )
  end
end
