update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_release do
    unlock_keychain
    cocoapods
    get_certificates
    get_provisioning_profile(
      app_identifier: "com.acceleratenetworks.linphone",
      cert_id: "84B763L3NG",
    )
    gym(
      clean: true,
      configuration: "Release",
      output_directory: "builds/",
      output_name: "an-mobile-release.ipa",
      scheme: "linphone",
      workspace: "linphone.xcworkspace",
      xcargs: "-allowProvisioningUpdates",
    )
  end
end
