update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_release do
    unlock_keychain
    cocoapods
    get_certificates
    get_provisioning_profile
    gym(
      clean: true,
      configuration: "Release",
      output_directory: "builds/",
      output_name: "an-mobile-release.ipa",
      scheme: "linphone",
      workspace: "linphone.xcworkspace",
    )
  end
end
