name: sync to gitlab
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: push to gitlab
        run: |
          git remote add gitlab https://${{ secrets.GITLAB_USER }}:${{ secrets.GITLAB_TOKEN }}@git.callpipe.com/AccelerateNetworks/an-mobile-ios.git
          git push gitlab "${GITHUB_REF}"
          git push --tags gitlab
